---
title: "CV"
author: "Aniruddha Ghosh"
email: A.Ghosh@cgiar.org
output:
  pdf_document:
    latex_engine: pdflatex
    template: rap-latex-cv.tex
  word_document: default
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
geometry: margin=1in
github: ani-ghosh
jobtitle: Associate Scientist
keywords: RMarkdown, academic CV, template
linkcolor: blue
orcid: orcid.org/0000-0003-3667-8019
fontawesome: yes
phone: +254 796 060763
address: Alliance of Bioversity International and CIAT Africa Hub, Nairobi, Kenya
updated: yes
urlcolor: blue
---

# EDUCATION

*TERI University*, Ph.D., Natural Resources Management \hfill 2014

*University of Delhi*, M.Sc. Physics \hfill 2009

*University of Calcutta*, B.Sc. Physics \hfill 2006

# EMPLOYMENT/ACADEMIC APPOINTMENT

*Alliance of Bioversity International and CIAT, Nairobi, Kenya: Associate Scientist* \hfill 2020--

 > Devlop novel monitoring toools for agricultural systems to better understand risk and shocks to support of development of adaptation and mitigation strategies 

 > Design big data analytics for farming and food systems
 
*University of Arkansas, Department of Agricultural Economics and Agribusiness, Fayetteville, Arkansas: Adjunct Faculty* \hfill 2021-- 

*University of California, Davis, California: Project Scientist*  \hfill 2015--2020

 > Develop big data and machine learning analytics tools for agriculture monitoring and crop yield prediction to support agriculture index insurance
 
 > Project management and coordinate collaborative research efforts of the \href{gfc.ucdavis.edu}{Geospatial and Farming Systems Research Consortium (GFC)}
 
 > Organize workshops on spatial data science for agriculture with free and open source tools

*Colorado State University, Fort Collins, Colorado: Postdoctoral Researcher*  \hfill 2014--2015 

 > Characterize post-fire vegetation recovery using remote sensing
 
*TERI University, New Delhi, India: Graduate Student Researcher*  \hfill 2009--2014

 >  Multi-sensor remote sensing image fusion for different environmental applications

*University of Freiburg, Freiburg, Germany: Visting Researcher*  \hfill 2012

 >  Hyperspectral and LiDAR data analysis for forestry applications

# PUBLICATIONS

## **Journal Articles (published/Accepted)**
  > Manners, R., Adewopo, J., Niyibituronsa, M., Remans, R., Ghosh, A., Schut, M., Egoeh, SG., Kilwenge, R., Fraenzel, A., Leveraging digital tools and crowdsourcing approaches to generate high-frequency data for diet quality monitoring at population scale in Rwanda. \emph{Frontiers In Sustainable Food Systems, accepted}. 
  
  > Kenduiywo, B., Ghosh, A., Carter, MR., Hijmans, RJ., Evaluating the Quality of Remote Sensing Products for Agricultural Index Insurance. \emph{PLoS ONE}, 16(10), 2021. 
  
 > Benami, E., Jin, Z., Carter, MR., Ghosh, A., Hijmans, RJ., Hobbs, A., Kenduiywo, B., Lobell, DB., Uniting remote sensing, crop modeling, and economics for agricultural risk management. \emph{Nat Rev Earth Environ}, 2021.
 
 > Wang, H., Ghosh, A., Linquist, BA., Hijmans, RJ., Satellite-Based Observations Reveal Effects of Weather Variation on Rice Phenology. \emph{Remote Sensing}, 12(9), 2020.

 > Smith, J., Ghosh, A., Hijmans, RJ., Agricultural intensification is associated with crop diversification in India. \emph{PLoS ONE}, 14(12), 2019.

 > Marshall, M., Crommelinck, S., Kohli, D., Perger, C., Yang, M., Ghosh, A., Fritz, S., de Bie, K., Nelson, A. Crowd-driven and automated mapping of field boundaries in highly fragmented agricultural landscapes of Ethiopia with very high spatial resolution imagery. \emph{Remote Sensing}, 11(18), 2019.

 > Shew, A., Ghosh, A., Identifying Dry Season Rice Planting Patterns in Bangladesh using the Landsat Archive. \emph{Remote Sensing}, 11(10), 2019.

 > Shew, A., Durand-Morat, A., Putman, B., Nalley, L.L., Ghosh, A., Rice Intensification in Bangladesh Improves Economic and Environmental Welfare. \emph{Environmental Science and Policy}, 95, 46--57, 2019.

 > Chakraborty, A., Ghosh, A., Sachdeva, K., Joshi, PK., Characterizing fragmentation trends of the Himalayan forests in the Kumaon region of Uttarakhand, India. \emph{Ecological Informatics}, 38, 95--109, 2016.

 > Fassnacht, FE., Latifi, H., Stere{\'n}czak, K., Modzelewska, A., Lefsky, M., Waser, LT., Straub, C., Ghosh, A., Review of studies on tree species classification from remotely sensed data. \emph{Remote Sensing of Environment}, 186(1), 64--87, 2016.

 > Ghosh, A., Joshi, PK., Hyperspectral imagery for disaggregation of land surface temperature with selected regression algorithms over different land use land cover scenes. \emph{ISPRS Journal of Photogrammetry and Remote Sensing}, 96, 76--93, 2014.

 > Fassnacht, FE., Neumann, C., Forster, M., Buddenbaum, H., Ghosh, A., Clasen, A., Joshi, PK., Koch, B., Comparison of Feature Reduction Algorithms for Classifying Tree Species With Hyperspectral Data on Three Central European Test Sites. \emph{IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing}, 7(6), 2547--2561, 2014.

 > Ghosh, A., Sharma, R., Joshi, PK., Random forest classification of urban landscape using Landsat archive and ancillary data: Combining seasonal maps with decision level fusion. \emph{Applied Geography}, 48, 31--41, 2014.

 > Fassnacht, FE., Latifi, H., Ghosh, A., Joshi, PK., Koch, B., Assessing the potential of hyperspectral imagery to map bark beetle-induced tree mortality. \emph{Remote Sensing of Environment}, 140, 533--548, 2014.

 > Ghosh, A., Joshi, PK., A comparison of selected classification algorithms for mapping bamboo patches in lower Gangetic plains using very high resolution WorldView 2 imagery. \emph {International Journal of Applied Earth Observation and Geoinformation}, 26, 298--311, 2014.

 > Ghosh, A., Fassnacht, FE., Joshi, PK., Koch, B., ``A framework for mapping tree species combining hyperspectral and LiDAR data: Role of selected classifiers and sensor across three spatial scales." \emph {International Journal of Applied Earth Observation and Geoinformation}, 26, 49--63, 2014.

 > Ghosh, A., Joshi, PK., Assessment of pan-sharpened very high-resolution WorldView-2 images. \emph{International Journal of Remote Sensing}, 34(23), 8336--8359, 2013.

 > Chakraborty, A., Joshi, PK., Ghosh, A., Areendran, G., Assessing biome boundary shifts under climate change scenarios in India. \emph{Ecological Indicators}, 34, 536--547, 2013.

 > Joshi, PK., Ghosh, A., Chakraborty, A., Sharma, R., Joshi, A., Landsat again – continuing remote sensing, monitoring, mapping and measuring. \emph{Current Science}, 105(6), 761--763, 2013.

 > Biswal, S., Ghosh, A., Sharma, R., Joshi, PK., Satellite Data Classification Using Open Source Support. \emph{Journal of the Indian Society of Remote Sensing}, 41(3), 523--530, 2013.

 > Sharma, R., Ghosh, A., Joshi, PK., Analysing spatio-temporal footprints of urbanization on environment of Surat city using satellite-derived bio-physical parameters. \emph{Geocarto International}, 28(5), 420--438, 2013.

 > Ghosh, A., Joshi, PK., Remote sensing of moving objects. \emph{Current Science}, 104(12), 1613--1615, 2013.

 > Ghosh, A., Joshi, PK., Garg, RD., Mukherjee, S., Identification of invasive plant species using field spectro-radiometer and simulated Hyperion spectra -- a rapid mapping of invasiveness. \emph{Current Science}, 104(9), 1148--1151, 2013.

 > Mukherjee, S., Joshi, PK., Mukherjee, S., Ghosh, A., Garg, RD., Mukhopadhyay, A., Evaluation of vertical accuracy of open source Digital Elevation Model (DEM). \emph {International Journal of Applied Earth Observation and Geoinformation}, 21, 205--207, 2013.

 > Sharma, R., Ghosh, A., Joshi, PK., Decision tree approach for classification of remotely sensed satellite data using open source support. \emph{Journal of Earth System Science}, 122(5), 1237--1247, 2013.

 > Sharma, R., Ghosh, A., Joshi, PK., Spatio-temporal footprints of urbanisation in Surat, the Diamond City of India (1990--2009). \emph {Environmental monitoring and assessment}, 185(4), 3313--3325, 2013.

 > Ghosh, A., Munshi, M., Areendran, G., Joshi, PK., Pattern space analysis of landscape metrics for detecting changes in forests of Himalayan foothills. \emph{Asian Journal of Geoinformatics}, 12(1), 2012.

 > Joshi, PK., Narula, S., Rawat, A., Ghosh, A., Landscape characterization of Sariska National Park (India) and its surroundings. \emph{Geo-spatial Information Science}, 14(4): 303--310, 2011.

 > Munsi, M., Areendran, G., Ghosh, A., Joshi, PK.,  Landscape characterisation of the forests of Himalayan foothills. \emph{Journal of the Indian Society of Remote Sensing}, 38(3):441--31452, 2010.

## **Journal Articles (under review)**
 > Ochoa-Brito, JI., Ghosh, A., Hijmans, RJ., Cropland expansion in Ecuador between 2000 and 2016. \emph{in review: Remote Sensing}.

 > Springborn, MR., Weill, JA., Lips, KR., Ibanez, R., Ghosh, A., Amphibian Collapses Exacerbated Malaria Outbreaks in Central America. \emph{in review: Proceedings of the National Academy of Sciences of the United States of America}.
  
 > Collins, A., Grote, M., Caro, T., Ghosh, A., Thorne, J., Mulder, MB., How community forest management performs when REDD+ payments fail. \emph{in review: Environmental Research Letters}.

## **Working Paper/Report**

 > Ghosh, A., Chamberlin, J., McDonald, A., Sonder, K., Vanlauwe, B., Prioritization of target geographies for Excellence in Agronomy One CGIAR global initiative, 2021.

 > Jarvis, A., Rosenstock, T., Koo, J., Thornton, P., Loboguerrero, A., Govaerts, B., Ramírez-Villegas, J., Prager, SD., Ghosh, A., Fuglie, K., Climate-informed priorities for One CGIAR Regional Integrated Initiatives. \emph{CGIAR Research Program on Climate Change, Agriculture and Food Security (CCAFS)}, 2021.

 > Koo, J., Azzarri, C., Ghosh, A., Quabili, W., Assessing the risk of COVID-19 in Feed the Future countries. \emph{GCAN Policy Note 13. Washington, DC: International Food Policy Research Institute (IFPRI)}, https://doi.org/10.2499/p15738coll2.134271, 2021.

 > Koo, J., Azzarri, C., Ghosh, A., Quabili, W., Assessing the risk of COVID-19 in Bangladesh. \emph{International Food Policy Research Institute (IFPRI)}, 2021.

 > Koo, J., Azzarri, C., Ghosh, A., Quabili, W., Assessing the risk of COVID-19 in Ethiopia. \emph{International Food Policy Research Institute (IFPRI)}, 2021.

 > Koo, J., Azzarri, C., Ghosh, A., Quabili, W., Assessing the risk of COVID-19 in Ghana. \emph{International Food Policy Research Institute (IFPRI)}, 2021.

 > Ramirez-Villegas, J., Ghosh, A., Craparo, S., Thornton, P., Manvatkar, R., Bogart, B., Läderach, P., Climate change and its impacts in Southern Africa: A synthesis of existing evidence in support of the World Food Programme’s 2021 Climate Change. \emph{Position Paper. CGIAR Research Program on Climate Change, Agriculture and Food Security Working Paper}, 2021.
 
 > Ramirez-Villegas, J., Rosenstock, TS., Steward, P., Bonilla-Cedrez, C., Notenbaert, AMO., Flintan, F., Crane, TA., Arango, J., Louhaichi, M., Bullock, RM., & others. Data and evidence-driven assessment of priorities for the Livestock, Climate and System Resilience (LCSR) One CGIAR global initiative, 2021.
 
## **Book Chapter**

 > Koo, J., Kramer, B., Langan, S., Ghosh, A., Gardeazabal Monsalue, A., Lunt, T. (forthcoming), Digital innovations for climate-resilient agri-food systems, \emph{Global Food Policy Report}, 2022.

## **Proceedings**

 > Kenduiywo, B., Ghosh, A., Hijmans, RJ., Ndungu,L., Rapid Maize Yield Estimation in Kenya Using MODIS, \emph{ISPRS proceedings of the 2020 edition of the XXIVth congress}, 2020. 

 > Shew, A., Ghosh, A., Using multi-temporal remote sensing data to understand the spatio-temporal patterns of dry season rice production in Bangladesh. \emph{ISPRS Annals of the Photogrammetry, Remote Sensing and Spatial Information Sciences, Volume IV-4/W2}, 2017.
 
 > Ghosh, A., Fassnacht, FE., Joshi, PK., Koch, B., Tree species mapping using multi-sensor (hyperspectral \& LiDAR) data: Effect of sensor, scale, and classifier. \emph{Land-use Related Biodiversity in India: Seminar Proceedings}, 2014.
 
  > Ghosh, A., Joshi, PK., Identification of bamboo patches in the lower Gangetic plains using very high resolution WorldView 2 imagery. \emph{Proc. SPIE 8893, Earth Resources and Environmental Remote Sensing/GIS Applications IV, 889310}, 2013.
 
# TEACHING

## **Courses**

*University of California, Davis* \hfill 2016--2018

> Co-instructor in Environmental Analysis using GIS and Quantitative Geography
  
*TERI University, India* \hfill 2011--2014

> Designed and taught courses on Applied Mathematics, Advances in Remote Sensing and Digital Image Processing & Information Extraction 

## **Workshops/ Training**

 > Free and Open Source Software for AgroGeoinformatics (FOSS4AG), Dhaka, Bangladesh, February 2020.

 > Spatial Data Analysis with R and Remote Sensing with Google Earth Engine, Ibadan, Nigeria, January 2020.  
 > Using R as an Open Source Geographic Information System, 2019 Training & Symposium Arkansas GIS Users Forum, Eureka Springs, AR, October 2019. 

 > Spatial Distribution Modeling with R, GeoVet 2019, Davis, CA, October 2019.

 > Remote sensing for agricultural insurance, RCMRD, Nairobi, Kenya, July 2019.

 > Spatial analysis with R, Phnom Penh, Cambodia, December 2018.

 > 2\textsuperscript{nd} International Workshop on Advanced R \& R-QTL, ICRISAT, India, December 2018.

 > Program committee for CGIAR-SIIL track, FOSS4G 2018, (Free and Open Source For Geospatial 2018), Tanzania, August 2018.

 > Spatial Data Analysis and Modeling for Agricultural Development, with R. Tanzania, August 2016.

 > Introduction to Google Earth Engine platform: Introduction and hands-on workshop, Davis, CA, April 2016.

# Sponsored Research and Programs

 > \emph{Scaling Financial and Information Services for Smallholder Adaptation}, funded by the \href{https://www.thegef.org/}{Global Environment Facility (GEF)}; PI. 
 
  > \emph{Prioritization module for Excellence in Agronomy}, funded by the \href{https://www.iita.org/iita-project/cgiar-excellence-in-agronomy-2030-incubation-phase/}{CGIAR Excellence in Agronomy 2030}; PI. 
 
 > \emph{Developing rapid digital analytics to understand and mitigate the effect of COVID-19 on farming communities}, funded by the \href{https://bigdata.cgiar.org/inspire}{The CGIAR Platform for Big Data in Agriculture}; PI. 
 
  > \emph{Citizen H2D3}, funded by the \href{https://bigdata.cgiar.org/inspire/rapid-response-grants/}{The CGIAR Platform for Big Data in Agriculture}.
 
 > \href{gfc.ucdavis.edu}{Geospatial and Farming Systems Research Consortium (GFC)}, funded by the \href{https://www.k-state.edu/siil/index.html}{USAID Feed the Future Innovation Lab for Sustainable Intensification}; Program coordinator. \hfill {July 2015 to Sep 2019}

 > \emph{Developing Advanced Index-Insurance Products for Ghanaian Smallholder Farmers}, funded by the
 \href{https://basis.ucdavis.edu/}{USAID Feed the Future Innovation Lab for Assets and Market Access}; Co-I. \hfill {May 2019 to December 2019}

 > \emph{High spatial resolution maize distribution and yield maps for Tanzania}, funded by the \href{https://basis.ucdavis.edu/}{USAID Feed the Future Innovation Lab for Assets and Market Access}; Co-I. \hfill {May 2018 to Dec 2019}

 > \emph{Climate change impact on rice yield and food security in the riverine communities in Cambodia}, funded by the \href{http://sites.nationalacademies.org/pga/peer/index.htm}{USAID PEER}; Co-I. \hfill {November 2018 - October 2020} 
 
# Technical Skills

## **Computational**

 > Programming Languages: R, Python, JavaScript

 > Remote Sensing Image Processing: Google Earth Engine APIs, ENVI-IDL,ERDAS-Imagine, PCI-Geomatica, eCognition, Pix4D

 > Other: ArcGIS, QGIS, Fragstats, ImageJ

## **Software Development**

 > \href{https://cran.r-project.org/web/packages/raster/index.html}{raster : Geographic Data Analysis and Modeling} (contributor) 
 > \href{https://github.com/rspatial/luna}{luna : satellite remote sensing tools}(co-author)

## **Equipment**

 > Unmanned Aerial Vehicle (UAV) for agricultural applications
 > ASD Field spectroradiometer, LiCOR Plant Canopy Analyzer

# AWARDS

## **Fellowships**

 > Junior and Senior Research Fellowship, CSIR, Government of India\hfill 2009 -- 2014 

 > Merit Scholarship from \emph{Minist{\`e}re de l\`{}{\'E}ducation, du Loisir	et du	Sport	du Qu{\'e}bec} for Post-Doctoral Research at McGill University, Canada \emph{(not availed)}\hfill 2014

 > DAAD Exchange Fellowship for PhD Students\hfill Sep 2012 -- Nov 2012

## **Travel**

 > Academic Federation Faculty Research Travel Grant, UC Davis for Participating in FOSS4G Annual Conference, Dar es Salaam, Tanzania\hfill August 2018

 > Young	Scientist Travel Fellowship	Award, SERB (DST-India) for	Participating in SPIE Remote Sensing conference, Dresden, Germany\hfill Sep 2013

 > SPIE Travel Grant\hfill Sep 2013

## **Data/Instrument**

 > DigitalGlobe Imagery Grant, Alexander Goetz Instrument Support Program \emph{(not availed)} \hfill 2012

# PRESENTATIONS

## **Conference**

 > Kramer, T., Tabalia, A., de Heu, R., Ghosh, A., Operational Agricultural Index Insurance for Kenyan Smallholder Farmers Based on Satellite Derived Soil Moisture. \emph{AGU Fall Meeting 2020}
 
 > Shew, AM., Ghosh, A., Track, JB., Nalley, LL., Estimating Crop Planting Delays and Phenological Variation caused by Extreme Rainfall Events in the US Lower Mississippi River Basin using Earth Observation Systems. \emph{AGU Fall Meeting 2019}

 > Wang, H., Ghosh, A., Hijmans, RJ., Climate-Driven Changes in Rice Phenology in California. \emph{AGU Fall Meeting 2019}

 > Springborn, M.R., Weill, J.A., Lips, K.R., Ibanez, R.,Ghosh, A., Ecosystem Service Impacts of Ecological Disruption: Evidence from Malaria Incidence in Central America. \emph{GeoVet 2019. Novel spatio-temporal approaches in the era of Big Data, Davis, CA}

 > Shew, AM., Owens, P.R., Ghosh, A., Solving Agricultural and Environmental Problems: GIS Today and Tomorrow. \emph{AR GIS Users Forum and OPENGATE Outreach Partnership Conference, Little Rock, AR}. \hfill {Nov, 2018}

 > Wang, H., Ghosh, A., Mapping paddy rice cropping pattern and phenology in Cambodia. \emph{FOSS4G 2018, Dar es Salaam, Tanzania.} \hfill{Aug 2018}

 > Lwehabura, J., Stewart, ZP., Rubyogo, JC., Prasad, PVV., Mason, N., Ghosh, A., Geospatial Analysis to Spur Technology Adoption for Increasing Bean Productivity in Tanzania. \emph{FOSS4G 2018, Dar es Salaam, Tanzania.} \hfill{Aug 2018}

 > Tiedeman, K., Ghosh, A., Landcover classification with R and Google Earth Engine to predict Human-elephant conflict. \emph{FOSS4G 2018, Dar es Salaam, Tanzania.} \hfill{Aug 2018} 

 > Lwehabura, J., Stewart, ZP., Rubyogo, JC., Prasad, PVV., Ghosh, A., Mason, N., Increasing Technology Adoption and Scaling through Mother-Baby Trials Paired with Geospatial Analysis of Enabling Biophysical and Socioeconomic Conditions. \emph{ 1st International Sustainable Agricultural Intensification and Nutrition (SAIN) Conference, Phnom Penh, Cambodia}. \hfill{Jan 2018}.

 > Shew, AM., Ghosh, A., Durand-Morat, A., Nalley, L.L., Food security impacts from the adoption of dry season hybrid and HYV rice production in Bangladesh.\emph{3rd International Conference on Global Food Security, Cape Town, South Africa}. \hfill{Dec 2017}.

 > Ghosh, A., Mandel, A., Hijmans, RJ., Developing Scalable Information Extraction Processing Pipelines using R for Earth Observation Applications.\emph{FOSS4G 2017, Boston, USA.} \hfill{Aug 2017}

 > Mandel, A., Ghosh, A., Hijmans, RJ., Rspatial.org, tutorials for learning Spatial R.\emph{FOSS4G 2017, Boston, USA.} \hfill{Aug 2017}
 
 > Shew, A., Ghosh, A., Using multi-temporal remote sensing data to understand the spatio-temporal patterns of dry season rice production in Bangladesh.\emph{2\textsuperscript{nd} International Symposium on Spatiotemporal Computing, Boston, USA.} \hfill{Aug 2017}

 > Ghosh, A., Joshi, PK., Identification of bamboo patches in the lower Gangetic plains using very high resolution WorldView 2 imagery. \emph{SPIE Remote Sensing, Dresden, Germany.} \hfill{Sep 2013}

 > Fassnacht, FE., Latifi, H., Ghosh, A., Joshi, PK., Koch, B., Assessing the potential of hyperspectral imagery to map bark beetle-induced tree mortality. \emph{SPIE Remote Sensing, Dresden, Germany.} \hfill{Sep 2013}

 > Ghosh, A., Fassnacht, FE., Joshi, PK., Koch, B., Tree species	mapping using Hyperspectral	imagery: effect	of scale and classifier. \emph{ 8\textsuperscript{th} EARSeL Imaging Spectrometry Workshop, Nantes, France.} \hfill{April 2013}

 > Chakraborty, A., Joshi, PK., Ghosh, A., Areendran, G., Mapping biomes of India using Holdridge Life Zone Model -- identifying footprints of climate change. \emph{13\textsuperscript{th} ESRI India User Conference.} \hfill{2012}

 > Sharma, R., Joshi, PK., Ghosh, A., Green and Grey Mosaics of Sustainable Urban Society. \emph{Planet Under Pressure, London.}\hfill{2012}
 
## **Invited**

 > Ghosh, A., Remote Sensing Image Processing with Open Source Software. \emph{Sacramento GIS User Group, CA.} \hfill{Jan 2019}

 > Ghosh, A., Mapping Surface Water Change with Google Earth Engine. \emph{Maptime Davis, CA.} \hfill{April 2018}

 > Hollarsmith, J., Tiedeman, K., Ghosh, A., Remote Sensing of Kelp: preliminary results and challenges. \emph{Puget Sound Kelp Recovery Plan Workshop WebEx.} \hfill{Mar 2018}

 > Shew, A., Durand-Morat, A., Putman, W., Nalley, L., Ghosh, A., Estimating Global Food Security Impacts from Hybrid and HYV Rice Adoption in Bangladesh. \emph{International Hybrid Rice Symposium in Yogyakarta, Indonesia.} \hfill{Feb 2018} 

 > Shew, A., Ghosh, A., Identifying Dry Season Rice Areas in Bangladesh at 30 m Resolution Using the Landsat Archive, Time Series Analysis, and Google Earth Engine. \emph{International Hybrid Rice Symposium in Yogyakarta, Indonesia.} \hfill{Feb 2018}

 > Ghosh, A., Finding Remote Sensing Data. \emph{Maptime Davis, CA.} \hfill{Feb 2018}

 > Ghosh, A., Using OpenStreetMap Data. \emph{Maptime Davis, CA.} \hfill{Dec 2017}

 > Ghosh, A. The U.S. Government's Global Food Security Research Strategy: From Upstream Research to Development Impact, \emph{Board for International Food and Agricultural Development (BIFAD) public meeting, Washington, DC.} \hfill{Sep 2017} 

 > Ghosh, A., Mandel, A., Hijmans, RJ., Geospatial Consortium, \emph{USAID Workshop on Innovation for Data-Driven Agriculture, Boulder, CO.} \hfill{April 2017}

# PROFESSIONAL SERVICE

## **Academic**
 > Guest Editor, \emph{Frontiers in Sustainable Food Systems, Remote Sensing}
 > Coordinator, Center for Spatial Sciences, University of California, Davis, hfill{2015 -- 2020}

 > Scientific Committee member of the Academic Track of FOSS4G 2018 (Free and Open Source For Geospatial 2018), Tanzania, August 2018

## **Journal Reviewer** \hfill {2011 -- }

 > \emph{Advances in Space Research, Applied Geography, Applied Sciences, Arabian Journal of Geosciences, Canadian Jounral of Remote Sensing, Development Engineering, Ecological Indicators, Egyptian Journal of Remote Sensing, Environmental Earth Sciences, Environmental Research Letters, European Journal of Remote Sensing, Geocarto International, GIScience \& Remote Sensing, IEEE Transactions on Geoscience and Remote Sensing, International Journal of Applied Earth Observation and Geoinformation, International Journal of Image and Data Fusion, International Journal of Remote Sensing, ISPRS Journal of Photogrammetry and Remote Sensing, Journal of Applied Remote Sensing, Landscape and Urban Planning, PeerJ, Remote Sensing Applications: Society and Environment, Remote Sensing of Environment, Remote Sensing, Sensors, Tropical Ecology}
 
# OUTREACH

## **Online training materials**

 >  \href{https://rspatial.org/}{Spatial Data Science with R} (co-author);
 
 >  \href{https://reagro.org/}{Regional Agronomy} (contributor);
 
 >  \href{https://www.youtube.com/watch?v=oosUzVJbExg}{Webinar - Agricultural Monitoring with Planet Data};
 
 >  \href{https://gfc.ucdavis.edu/events/agrin/html/}{Remote sensing for agricultural insurance} (co-author)

## **Public media**

 > \href{https://www.ifpri.org/blog/rural-populations-face-heightened-covid-19-risks}{Rural populations face heightened COVID-19 risks};
 
 > \href{https://www.youtube.com/watch?v=5b2xhqlH49I}{Terra and Luna: New R packages scalable geospatial data analysis - 2020 Convention session};
 
 > \href{https://www.youtube.com/watch?v=-gvhZwwgF_Q}{Explore the GARDIAN Ecosystem with us! - 2020 Convention session};
 
 >  \href{https://blogs.k-state.edu/siil/2017/11/20/worldclim2/}{WorldClim 2: High Resolution Climate Surfaces for Global Land Areas};
 
 >  \href{https://blogs.k-state.edu/siil/2018/06/06/conservation-challenges-for-sustainable-intensification-of-agriculture-in-africa/}{Conservation Challenges for Sustainable Intensification of Agriculture in Africa}
 